"""Brandbot 프롬프트 패키지 초기화."""

from __future__ import annotations

from .llm_prompts import (
    CLASSIFY_INTENT_PROMPT,
    CLASSIFY_SCOPE_PROMPT,
    EXTRACT_KEYWORDS_FROM_SLOGAN_PROMPT,
    EXTRACT_REQUIRED_PROMPT,
    EDIT_TARGET_PROMPT,
    MAP_DOC_TO_BRIEF_PROMPT,
    NAME_EXPLICIT_PROMPT,
    REDUCE_DOCS_TO_RECOS_PROMPT,
    TREND_EDIT_PROMPT,
)

__all__ = [
    "CLASSIFY_SCOPE_PROMPT",
    "CLASSIFY_INTENT_PROMPT",
    "NAME_EXPLICIT_PROMPT",
    "EXTRACT_REQUIRED_PROMPT",
    "EDIT_TARGET_PROMPT",
    "EXTRACT_KEYWORDS_FROM_SLOGAN_PROMPT",
    "TREND_EDIT_PROMPT",
    "MAP_DOC_TO_BRIEF_PROMPT",
    "REDUCE_DOCS_TO_RECOS_PROMPT",
]

